### ISSUE TITLE
大佬，运行有报错，求指教

### ISSUE THREAD

**Issue by 19819068211** [shanghua520/fuck-hexue-class-time#1]
作者大大，运行有拆报错，具体如下图，求求大佬解决办法

Traceback (most recent call last):
  File "/data/data/com.termux/files/home/fuck-hexue-class-time/main.py", line 107, in <module>
    logininfo = login('username', 'password', None)
  File "/data/data/com.termux/files/home/fuck-hexue-class-time/main.py", line 13, in login
    logininfo = json.loads(reps)
  File "/data/data/com.termux/files/usr/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/data/data/com.termux/files/usr/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/data/data/com.termux/files/usr/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

![Screenshot_20210623_112903_com termux](https://user-images.githubusercontent.com/66981884/123032142-0d289880-d418-11eb-9a6e-673f67e3484d.jpg)

**Comment by shanghua521** [comment]
我这玩意万年没更新了，应该已经不能用了
